Add files via upload
PERFECTHEART/industrial_cpp_vk pull request #13
Opened 2023-06-01 00:43 UTC by PERFECTHEART

2023-06-01 09:16 UTC, namitmax requested changes

2023-06-01 09:16 UTC, namitmax commented on hw1/include/ustring.hpp
> -		bool operator==(const Iterator& rhs) const { return str_ ==  rhs.str_ && curr_pos_ == rhs.curr_pos_; }
а вот здесь у нас friend уже нет, хотя, возможно нужен, или нет?

2023-06-01 09:16 UTC, namitmax commented on hw1/include/ustring.hpp
>  {
не очень понял на 41й строке про какую унификацию методов идет речь? И если там внутри ифа не может быть пустой строки зачем проверка на len > 0 + если даже len == 0 цикл просто ничего не сделает?

2023-06-01 09:16 UTC, namitmax commented on hw1/include/ustring.hpp
>  	}
а почему в UString &operator =(const std::string &str) нельзя просто использовать конструктор копирования и вернуть элемент , плюс в таком подходе - избегаем дублирования логики ?

2023-06-01 09:16 UTC, namitmax commented on hw1/include/ustring.hpp
>  	}
чем на 143й строке эффективнее передача по значению?

2023-06-01 09:16 UTC, namitmax commented on hw1/include/ustring.hpp
>  		return ret;
data_[it] точно всегда существует - не можем выйти за границы массива , или, мб нужна проверка все же?

2023-06-01 09:16 UTC, namitmax commented on hw1/include/ustring.hpp
>  		data_.erase(last, data_.end());
немного странно выглядит 	assert(last != data_.begin()) в теле цикла .

2023-06-01 16:37 UTC, PERFECTHEART commented on hw1/include/ustring.hpp
> +		if(!str.empty())
Если переменной присваивается пустая строка, data_ очистится и не будет попыток запустить цикл. Сразу - return.

2023-06-01 16:39 UTC, PERFECTHEART commented on hw1/include/ustring.hpp
> +	friend UString operator +(UString lhs, const UString &rhs) noexcept
Без "friend" при компиляции получаем ошибку: error: ‘UString UString::operator+(UString, const UString&)’ must have either zero or one argument
Для оператора был выбран вариант вне класса, ради возможности неявного преобразование (не реализовано).

2023-06-01 16:40 UTC, PERFECTHEART commented on hw1/include/ustring.hpp
>  	}
По условиям задачи конструктор копирования не требовался, поэтому он и не был реализован.

"UStirng
Напишите аналог std::string, но предполагающий, что внутри - UTF-8.
Соответственно, нужно будет добавить/исправить методы:
1. length() - число U8-символов
2. push_back(char32_t) - добавляет юникод по codepoint
3. pop_back() - должен удалять последний символ (а не байт)
4. is_well() - проверяет, является ли utf-8 строка корректной
5. Итераторы - ходят по utf-8 символам"

Реализована версия с базовым функционалом. Но это, разумеется, не полный аналог класса std:string.

2023-06-01 16:44 UTC, PERFECTHEART commented on hw1/include/ustring.hpp
>  	}
Выполнил тесты для gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) и выяснил, что иногда передача по значению
работает быстрее, чем по ссылке, а иногда - наоборот. Но при оптимизации -O3 - разница всегда в пользу ссылки. 
Код исправлен.

2023-06-01 16:44 UTC, PERFECTHEART commented on hw1/include/ustring.hpp
> +		if(!str.empty())
Если переменной присваивается пустая строка, data_ очистится и не будет попыток запустить цикл. Сразу - return.

2023-06-01 16:45 UTC, PERFECTHEART commented on hw1/include/ustring.hpp
>  {
1) Ранее этот метод копировал строку std::string &str в data_ "в лоб". При этом допускалась инициализация текстом с содержимым, не соответствующим utf8 кодированию и метод is_well(), который требовалось реализовать по условию задания, выявлял такое несоответствие. Сейчас строка наполняется посимвольно через "push_back()" аналогично конструктору для аргумента std::u32string и оператору присваивания, а метод is_well() стал бесполезным.
2) if на 41 строке - лишний, согласен. Убрал его.

2023-06-01 16:45 UTC, PERFECTHEART commented on hw1/include/ustring.hpp
>  		return ret;
data_[it] в текущей реализации и с данным набором тестов не столкнулся с выходом за границу массива, но добавил проверку в виде assert().

2023-06-01 16:46 UTC, PERFECTHEART commented on hw1/include/ustring.hpp
>  		data_.erase(last, data_.end());
data_.begin() вынес из цикла. В целом, данный assert является формальностью, т.к. строка data_ в данной реализации всегда корректна с точки зрения кодировки utf8.

2023-06-01 17:31 UTC, namitmax commented on hw1/include/ustring.hpp
> +	friend UString operator +(UString lhs, const UString &rhs) noexcept
Ошибка компиляции понятно - а почему она возникает? в каком месте происходит преобразование ? Зачем все же это нужно?

2023-06-01 17:31 UTC, namitmax commented on hw1/include/ustring.hpp
> -		bool operator==(const Iterator& rhs) const { return str_ ==  rhs.str_ && curr_pos_ == rhs.curr_pos_; }
Давайте попробуем найти нечто общее между этими 2 примерами использования оператора == и понять в каких ситуациях следует использовать friend

2023-06-01 21:53 UTC, PERFECTHEART commented on hw1/include/ustring.hpp
> +	friend UString operator +(UString lhs, const UString &rhs) noexcept
Внутри класса можно использовать без friend только вариант с одним аргументом rhs. В качестве левого выступает this. 
friend оператор нужен для реализации операций над аргументами разных типов и предоставления доступа к приватным членам (вне класса).
friend внутри класса не имеет большого смысла, т.к. доступ к приватным членам уже есть.
Код исправил, убрал friend.

2023-06-01 21:56 UTC, PERFECTHEART commented on hw1/include/ustring.hpp
> -		bool operator==(const Iterator& rhs) const { return str_ ==  rhs.str_ && curr_pos_ == rhs.curr_pos_; }
friend оператор нужен для реализации операций над аргументами разных типов и предоставления доступа к приватным членам (вне класса).
В данном случае, по моему мнению, friend не нужен, как и в случае, который обсуждался выше.

2023-06-02 10:44 UTC, namitmax requested changes

2023-06-02 13:30 UTC, PERFECTHEART commented on hw1/include/ustring.hpp
>  		data_.erase(last, data_.end());
Если строка пустая - сразу возврат.
Начинаем цикл с позиции data_.end() - 1 - т.е. последний символ в строке.
Пока код символа соответствует продолжению 2..4-байтного UTF символа - смещаемся левее.
Как только эта цепочка закончилась - мы либо оказались в голове длинного символа,
либо на однобайтном символе. Его и всё, что после него удаляем из строки.
В цикле last никогда не станет равен data_.begin(), т.к. в этом случае сначала прервётся цикл while потому что первый символ не может быть продолжением, push_back не пропустит такой код.
Я решительно не понимаю, в чём проблема? Можете пояснить?

2023-06-03 11:43 UTC, PERFECTHEART commented on hw1/include/ustring.hpp
>  	}
Оператор присваивания для std::string и std::u32string теперь выполняются через "конструктор копирования". Код поправил.

2023-06-04 08:55 UTC, namitmax requested changes

2023-06-04 08:55 UTC, namitmax commented on hw1/include/ustring.hpp
>  	}
как то тут не видно (по крайней мере мне) статзначимого ускорения ни в одну сторону , каким образом вы пришли к вышеуказанному выводу по данному тесту ?

2023-06-04 08:55 UTC, namitmax commented on hw1/include/ustring.hpp
>  		data_.erase(last, data_.end());
Теперь стало понятнее, после того как все же получил пояснение . Вообще говоря, assert это не проверка вроде while (last != first) {--last} условно , это постулируемое выражение , невыполнение которого означает ошибку в работе самого алгоритма. Есть ощущение, что можно было бы перенести last != data_.begin() в условие цикла, и если пришли в begin кидать исключение а ля wrong string format . Но, это не так важно, нужны были именно пояснения, их я получил.

2023-06-04 08:55 UTC, namitmax commented on hw1/include/ustring.hpp
>  	}
Вероятно не совсем корретно выразился , в данном исполнении у нас происходят лишние действия в виде data_ = tmp.data_ (хотя там вроде string оно мувнется и все ок будет, но все же ). Думаю лучше использовать логику данного "конструктора" . А перенести саму логику как раз в оператор = . Конструктор сделать как 
1. очистка this (если по логике нужно - тут вам думаю виднее)
2. *this = other (используя как раз реализованный оператор)

2023-06-04 11:38 UTC, PERFECTHEART commented on hw1/include/ustring.hpp
>  {
Лишние операторы удалены.

2023-06-04 11:46 UTC, PERFECTHEART commented on hw1/include/ustring.hpp
>  	}
Копирование заменено на move. 
Утечки памяти нет. (valgrind её не показывает, т.к. не выделяется data_ динамически, а операторов new() нет)
При попытке очистки (delete) this нарушается работа программы.

2023-06-04 11:49 UTC, PERFECTHEART commented on hw1/include/ustring.hpp
>  	}
В данном случае "эффективнее передача по значению" было гипотезой, которую я проверял тестами. Я не могу сделать такой вывод после тестов. Действительно, статзначимого ускорения нет.
Передача по значению заменена передачей по ссылке.

2023-06-04 11:50 UTC, PERFECTHEART commented on hw1/include/ustring.hpp
>  		data_.erase(last, data_.end());
Исправил на вариант без assert в цикле.

2023-06-05 13:04 UTC, namitmax commented on hw1/include/ustring.hpp
>  	}
"разница всегда в пользу ссылки." и в итоге поменяли на ссылку, но это тоже, кажется, так не работает (код теста посмотрел - он не особо показателен на самом деле, можете например просто закоментить строку , которая меняется и посмотреть как изменится дельта времени) . Очень хочется, чтобы вы разобрались почему передача по ссылке или по значению здесь не играет роли, можете пересмотреть лекцию - там про это было.

2023-06-05 13:07 UTC, namitmax commented on hw1/include/ustring.hpp
>  	}
так , в данном случае, можно сделать. Но, в общем случае , не совсем верно , потому что кроме data в общем случае может быть еще много полей и как то не совсем хорошо выходит. Поправьте, пожалуйста, на вышеуказанный вариант.

2023-06-06 14:52 UTC, PERFECTHEART commented on hw1/include/ustring.hpp
>  	}
Насколько я понимаю, здесь это не играет, потому что переменная size_t весит 8 байт (в 20 убунте на intel-платформе). Размер ссылки тоже 8 байт, если я не ошибаюсь.

2023-06-06 17:27 UTC, PERFECTHEART commented on hw1/include/ustring.hpp
>  	}
Видимо, я неправильно вас изначально понял.
Для конструктора, содержащего динамические переменные требуется нетривиальный деструктор, который влечёт за собой необходимость реализации копирующих и присваивающих конструкторов и операторов. Для тестирования была введена переменная dummy_, добавлены недостающие элементы класса, выполнены проверки на утечку памяти (valgrind). Переменная больше не нужна и она удалена из кода вместе с деструктором.
Теперь код подготовлен для использовании динамических переменных, хотя первоначальную задачу он выполнял и без этого.

2023-06-08 10:37 UTC, namitmax commented on hw1/include/ustring.hpp
>  	}
Зачем вы ввели dummy_ , при чем тут утечки памяти , что значит "код подготовлен для использования динамических переменных, хотя первоначальную задачу он выполнял и без этого" . Я правда не понимаю как это связано с тем, что говорил я . 
Еще раз сформулирую о чем идет речь сейчас : есть две штуки UString &operator =(const std::string &str) , UString(const std::string &str) в которых было дублирование кода . Его надо избежать и это можно сделать тремя способами : 
1. вынести общую логику в отдельную функцию и как то ее использовать внутри данных методов
2. сделать оператор равно через конструктор
3. сделать конструктор через оператор равно .

Вы в какой то момент выбрали способ номер 2 , мне не очень понравилось , что в нем мы муваем член класс data как data = std::move(other.data) (допустим есть много полей у класса , все мувать подряд как то не оч в данном методе)  , я предложил вариант исправления заменив вариант 2 на 3. Что пошло дальше я искренне понять не могу - ни слова про утечки , динамические переменные и прочее здесь не было . Итого, пожалуйста, реализуйте один из 3 вариантов реализации данных методов .

2023-06-08 20:51 UTC, PERFECTHEART commented on hw1/include/ustring.hpp
>  	}
Реализован конструктор через оператор присваивания.

Я считал, что мувать нужно динамические переменные, поэтому я и ввёл dummy_ для полноты картины и для тестирования корректности кода.
Ну, это лично я так понял ваше замечание, поэтому не сразу заменил 2 вариант на 3.

2023-06-11 10:20 UTC, namitmax requested changes

2023-06-11 10:20 UTC, namitmax commented on hw1/include/ustring.hpp
> +	bool is_well() const noexcept
не уверен что noexcept , кажется как минимум std::distance не является noexcept

2023-06-11 10:20 UTC, namitmax commented on hw1/include/ustring.hpp
> +	size_t length() const noexcept
charlen не является noexcept

2023-06-11 10:20 UTC, namitmax commented on hw1/include/ustring.hpp
>  		data_.erase(data_.begin(), data_.end());
erase noexcept ?
Замечание общее - поправьте везде уровни гарантии исключений

2023-06-11 10:20 UTC, namitmax commented on hw1/include/ustring.hpp
> +		std::string::iterator tmp = data_.begin();
tmp боюсь здесь не самое информативное имя переменной

2023-06-11 13:10 UTC, PERFECTHEART commented on hw1/include/ustring.hpp
> +	size_t length() const noexcept
Поправил.

2023-06-11 13:12 UTC, PERFECTHEART commented on hw1/include/ustring.hpp
> +		std::string::iterator tmp = data_.begin();
Переименовал в save_begin на 342 строке и в current_char_len в 183 строке (там тоже было tmp)

2023-06-11 13:12 UTC, PERFECTHEART commented on hw1/include/ustring.hpp
> +	bool is_well() const noexcept
Убрал noexcept

2023-06-11 13:12 UTC, PERFECTHEART commented on hw1/include/ustring.hpp
>  		data_.erase(data_.begin(), data_.end());
Убрал noexcept

2023-06-15 11:12 UTC, namitmax requested changes

2023-06-15 11:12 UTC, namitmax commented on hw1/include/ustring.hpp
> +	UString(UString&& other)
а он разве не дефолтный ? Раньше вроде его не было

2023-06-15 11:12 UTC, namitmax commented on hw1/include/ustring.hpp
> +	UString(const UString& other)
аналогично про дефолтность

2023-06-15 11:12 UTC, namitmax commented on hw1/include/ustring.hpp
> +	UString& operator =(UString&& other)
опять же

2023-06-15 11:12 UTC, namitmax commented on hw1/include/ustring.hpp
> +		return this->data_ == rhs.data_;
зачем здесь this кстати ?

2023-06-15 17:32 UTC, PERFECTHEART commented on hw1/include/ustring.hpp
> +		return this->data_ == rhs.data_;
Не нужен, убрал

2023-06-15 17:33 UTC, PERFECTHEART commented on hw1/include/ustring.hpp
> +	UString& operator =(UString&& other)
Комментарий выше

2023-06-15 17:33 UTC, PERFECTHEART commented on hw1/include/ustring.hpp
> +	UString(const UString& other)
Комментарий выше

2023-06-19 14:16 UTC, namitmax approved these changes
удалить ненужный код, остальное кажется ок

2023-06-19 14:27 UTC, merged